# Generated by Django 4.1.7 on 2023-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="comment",
        ),
        migrations.AddField(
            model_name="blog",
            name="comment",
            field=models.TextField(default="hai"),
        ),
    ]
